### ISSUE TITLE
Call to execute() is slow

### ISSUE THREAD

**Issue by om26er** [lxc/pylxd#182]
Using pylxd 2.1, it seems the execute() call is quite slow and takes at least 5 seconds to finish. Not sure if its due to ws4py or something else.

**Comment by rockstar** [comment]
Can you provide more information? How long do you expect the command to take? Generally, the `execute` command is a thin layer around whatever you're executing, so if you did `my_container.execute(['sleep', '5'])` then it will surely take at least 5 seconds.

Do you get a different result when using `lxc exec`?

**Comment by om26er** [comment]
Hi! Sorry for the late response.

I executed the simplest command i.e. `ls` and it takes 5 seconds to finish. OTH lxc exec is instant as you would expect it to be. This issue was also verified by the Libertine developers as well.

**Comment by maikeueule** [comment]
Hi,

I still notice the same behaviour with your latest commit. While I cannot explain it, it seems that the websocket is not closed properly until we make a call to self.client.operations.get. This causes the while loop with the sleep to wait 5 seconds.

Even worse, since operations stay in LXD for about 5 seconds, it generally triggers a 'Not found' Error when further querying for the operation.

I am not sure whether my approach is good, but swapping the two following lines seems to make the job:
>         operation = self.client.operations.get(operation_id)
> 
>         while len(manager.websockets.values()) > 0:
>             time.sleep(.1)
