### ISSUE TITLE
Documentation is outdated

### ISSUE THREAD

**Issue by duk3luk3** [lxc/pylxd#260]
Happy new year! 🎉 

The documentation is in pretty bad shape. Example:

https://pylxd.readthedocs.io/en/latest/containers.html / https://github.com/lxc/pylxd/blob/master/doc/source/containers.rst:

> execute - Execute a command on the container. The first argument is a list, in the form of subprocess.Popen with each item of the command as a separate item in the list. Returns a two part tuple of (stdout, stderr). This method will block while the command is executed.

`container.py`:

https://github.com/lxc/pylxd/blob/8588c3afb316299f204ae502b1c35dd7d7e3420e/pylxd/models/container.py#L39-L41

https://github.com/lxc/pylxd/blob/8588c3afb316299f204ae502b1c35dd7d7e3420e/pylxd/models/container.py#L250-L251

Also:

https://github.com/lxc/pylxd/blob/8588c3afb316299f204ae502b1c35dd7d7e3420e/pylxd/models/container.py#L207-L212

Why is the documentation in the `doc` folder instead of inline? Why is even the inline documentation becoming outdated?

LXC is an amazing project (really!) and it is a shame that the documentation is not excellent.

Python documentation is not something I've done a lot of work with, but if anyone commits to making the technical process to generate docs and push them to readthedocs work, I would be willing to spend effort on moving the documentation from `doc/` to docstrings in the source and cleaning it up in the process.

**Comment by ajkavanagh** [comment]
Thanks @duk3luk3 for raising this issue; it is indeed very important that the documentation mirrors and explains/describes the API and functionality of pylxd (in this case).

> Why is the documentation in the doc folder instead of inline? Why is even the inline documentation becoming outdated?

I can't answer the first question, except that the documentation that you've pointed out is *probably* meant to be general information and 'how-to' type documentation, rather than specific API details; unfortunately, it got a bit *too* specific, and then became outdated.

The API documentation (on readthedocs) is taken from the code starting at: https://pylxd.readthedocs.io/en/latest/api.html

The API inline documentation can become outdated when commits are approved which change the API but those commits don't also include appropriate docstring changes.  This can happen because the reviewer doesn't 'see' the docstring when the changes are being made to the code as there are (sadly, in this example) no changes to the docstring, so they don't show up in the diff.  It's very easy to miss these things, and there's no silver bullet.

It's great that you *have* spotted the error and raised an issue; that's exactly what should happen in this case, and so thank you!

> LXC is an amazing project (really!) ...

I agree, and it's the work of many, many contributors to the project; 

> ... and it is a shame that the documentation is not excellent.

Indeed.

> Python documentation is not something I've done a lot of work with, but if anyone commits to making the technical process to generate docs and push them to readthedocs work, I would be willing to spend effort on moving the documentation from doc/ to docstrings in the source and cleaning it up in the process.

I don't think *all* the documentation should be moved from `doc/` to the docstrings, but I may be misunderstanding your thoughts here.  Some of that is documentation is general information about *what* the library is for and how the library works  I agree that the specifics of the API should definitely be in the docstrings, and also be correct.

I wasn't aware that the readthedocs push wasn't working.  That's something I'll have to investigate!

And, yes, it would be great if you do have some time to push on documentation issues; all help is **very** much appreciated.

**Comment by duk3luk3** [comment]
Hi, thanks for your response.

> I wasn't aware that the readthedocs push wasn't working. That's something I'll have to investigate!

I don't know that it isn't working, I haven't seen any discrepancies between what's in https://github.com/lxc/pylxd/tree/master/doc/source and what's on readthedocs.

The reason I mentioned that was that it looks to me like having the documentation separate from the source is one of the main sources of documentation getting outdated, and fixing that would probably require some technical work to change how the documentation is generated.

> I don't think all the documentation should be moved from doc/ to the docstrings, but I may be misunderstanding your thoughts here. Some of that is documentation is general information about what the library is for and how the library works I agree that the specifics of the API should definitely be in the docstrings, and also be correct.

I just dug into this a little deeper, and the best immediate course of action seems to be to improve the autodoc.

I'm a bit confused that none of the docstrings in https://github.com/lxc/pylxd/blob/master/pylxd/models/container.py are currently visible in https://pylxd.readthedocs.io/en/latest/api.html#container. Can you figure out why?

**Comment by ajkavanagh** [comment]
> I'm a bit confused that none of the docstrings in
> https://github.com/lxc/pylxd/blob/master/pylxd/models/container.py are currently visible in
> https://pylxd.readthedocs.io/en/latest/api.html#container. Can you figure out why?

Actually, I don't know.  I'll have to do some digging as to what's supposed to happen.  TBH, Sphinx is not my area of expertise; I'm going to have to do some reading!
