### ISSUE TITLE
Can't pass Nvidia GPU via config dict on container creation

### ISSUE THREAD

**Issue by Samin100** [lxc/pylxd#297]
I'm trying to use pylxd to create a container from a local image and give it access to 1 Nvidia GPU via the config dict, but I'm unsure if I'm doing things correctly. Here's what I have. `gpu_id` is an integer of the GPU ID I want to passthrough to the container. `container_name` and `image_fingerprint` are strings.

```
        gpu_name = str(gpu_id) + 'GPU'
        print(gpu_name)

        config = {
            'name': container_name,
            'source': {
                'type': 'image',
                'fingerprint': image_fingerprint
            },
            "devices": {
                gpu_name: {
                    "id": int(gpu_id),
                    "type": 'gpu'
                }
            }
        }

        print('creating container from image...')
        self.client.containers.create(config=config, wait=True)

        print('Created container')
```

This is the traceback when I try to create the container:
```

  File "/home/dev/vectordash/core/ContainerController.py", line 67, in create_container_from_image
    self.client.containers.create(config=config, wait=True)
  File "/usr/local/lib/python3.5/dist-packages/pylxd/models/container.py", line 181, in create
    response = client.api.containers.post(json=config)
  File "/usr/local/lib/python3.5/dist-packages/pylxd/client.py", line 134, in post
    self._assert_response(response, allowed_status_codes=(200, 201, 202))
  File "/usr/local/lib/python3.5/dist-packages/pylxd/client.py", line 91, in _assert_response
    raise exceptions.LXDAPIException(response)
pylxd.exceptions.LXDAPIException: json: cannot unmarshal number into Go value of type string
```

Here's my pylxd version (installed via pip3) and I'm running Ubuntu 16.04.
```
>>> pylxd.__version__
'2.2.6'
```

I'm pretty sure there's an error in my config dict, but I'm unsure where. Any pointers would be appreciated!

**Comment by ajkavanagh** [comment]
That error is coming back from lxd, so technically, it's not bug/issue in the pylxd library.  The configuration option is described here: https://github.com/lxc/lxd/blob/master/doc/containers.md#type-gpu

The bug is probably due to `gpu_name` being a mix of the id + "GPU".  However, even staring at the documentation and lxd code is giving me no clue as to what the format is for that.  So I've asked in channel: let you know what I learn.

**Comment by ajkavanagh** [comment]
So, @Samin100, something to try.  Instead of passing the 'int' of the GPU in id, pass it as a string:

```python
{
    ...
     "devices": {
        gpu_name: {
        "id": str(gpu_id),
        "type": 'gpu'
    }
}
```

The spec at https://github.com/lxc/lxd/blob/master/doc/containers.md#type-gpu indicates that the Type for `id` is a `string`.  Hope that this helps.  (Obviously, it may be a string already; I'm just doing it for completeness).

**Comment by Samin100** [comment]
It appears casting `gpu_id` as a string fixed the issue! Thanks for the speedy responses @ppkt and @ajkavanagh!
