### ISSUE TITLE
UserWarning is raised for attributes from lxd that pylxd doesn't have a mapping for

### ISSUE THREAD

**Issue by shuhaowu** [lxc/pylxd#301]
Everytime I call Container.get under Ubuntu Bionic, I'm getting `/usr/local/lib/python3.6/dist-packages/pylxd-2.2.6-py3.6.egg/pylxd/models/_model.py:116: UserWarning: Attempted to set unknown attribute "location" on instance of "Container"`. I assume this is an issue because lxd 3.0 is return a location attribute in the response json?

I can't easily confirm this right now as I'm on my travel setup, but I want to document this before I forget.

**Comment by ajkavanagh** [comment]
Yes, this is expected.  Due to the architecture of pylxd, it gets 'upset' when new attributes appear on objects that it is modelling.  Hence the warning.  Location is a new attribute on lxd 3.0 that isn't yet supported on pylxd 2.2.x

What really needs to happen is for pylxd to become less picky about what it will accept as an attribute, but that needs the architecture to be significantly changed (see #283 version 3.0 of pylxd), which would be a backwards incompatible change (but with legacy support).

In the interim, I'm adding the 'enhancement' tag, as it just needs the 'location' attribute added as an attribute to Container.

**Comment by ajkavanagh** [comment]
So, I'm wondering; is it more useful to *not* show the warnings when attributes that pylxd doesn't have (but lxd does) are attempted to be set?  i.e. to clean up the output, but not show the warning?

**Comment by ajkavanagh** [comment]
I have an alternative suggestion; suppress the warnings (about attributes) using an ENV var (default to generate warnings), and change the warning to something that indicates a later version of pylxd might include the attributes?
