### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by nanjj** [lxc/pylxd#350]
Error message:
```
  File "/usr/local/lib/python3.6/dist-packages/pylxd-2.2.7-py3.6.egg/pylxd/models/container.py", line 316, in stop
    wait=wait)
  File "/usr/local/lib/python3.6/dist-packages/pylxd-2.2.7-py3.6.egg/pylxd/models/container.py", line 291, in _set_state
    response.json()['operation'])
  File "/usr/local/lib/python3.6/dist-packages/pylxd-2.2.7-py3.6.egg/pylxd/models/operation.py", line 32, in wait_for_operation
    operation.wait()
  File "/usr/local/lib/python3.6/dist-packages/pylxd-2.2.7-py3.6.egg/pylxd/models/operation.py", line 62, in wait
    if response.json()['metadata']['status'] == 'Failure':
TypeError: string indices must be integers
```
To produce:
```
from pylxd import Client
client = Client()
c1 = client.containers.all()[0]
c1.stop(wait = True)
```
`lxd --version`:  3.9

**Comment by ajkavanagh** [comment]
Judging by the API for Operation (https://github.com/lxc/lxd/blob/master/doc/rest-api.md#10operationsuuid) this has been an issue for quite a while; which means that the tests are not picking it up.

So something has changed in the way that the `response.json()` is handling the metadata, which looks like `metadata` is now a string, rather than an object with a `secret` key.

Anyway, the code needs fixing so that it only checks for `response.json()['status']`.

**Comment by ajkavanagh** [comment]
I've just tried this again on a fresh machine and it seems to be working fine?  Which is very odd.  Please could you test this again and see if it's still a problem for you?  Thanks.

**Comment by ajkavanagh** [comment]
Closing as it doesn't seem to be an issue or isn't repeatable.  Please re-open if it occurs again.  Thanks.

**Comment by maxrbc** [comment]
I manage to get this error again while running a VM cluster running ubuntu18 with lxc version 3.0.3. When the master is waiting for a container to be created in a cluster member it pops this error again. Modifying the response.json by eliminating the read into attribute ' medatata' as [suggested ](https://github.com/lxc/pylxd/issues/350#issuecomment-452681683) and as per the API for Operation fixed the issue for me
